### ISSUE TITLE
Improve Data Styling

### ISSUE THREAD

**Issue by rajadain** [azavea/pwd-river-dispatches#12]
Currently it looks like this:

![image](https://user-images.githubusercontent.com/1430060/27233901-222b0e8a-5289-11e7-9020-13b8c6f2298a.png)

Improvements we may consider:

 * Making the text bigger
 * Making the text more centered
 * Using different fonts / styling

We should keep in mind that some units (for example for Salinity / Conductivity) can get pretty long.

We may consider changing what the units look like, for example using **℃** or **°C** instead of **deg C**.

In some cases, we may not want to show the units at all, such as pH where they come as **FNU**.

**Comment by rajadain** [comment]
Prefer using units that correspond with text already in the app.

**Comment by rajadain** [comment]
Consider making the live value not white, but a shade of the respective color.

**Comment by rajadain** [comment]
Add `The Schuylkill River today:` header before the value.

**Comment by rajadain** [comment]
Add subtext below the value: `This value is coming from a sensor nearby in the river` or something along those lines.

**Comment by kellyi** [comment]
Seemed like we should probably have a distinctive header/subtext for displaying fallback values, so I've temporarily written:

header: "Typical Schuylkill measurement:"
subtext: "A common sensor reading for this time of year."

**Comment by kellyi** [comment]
> Prefer using units that correspond with text already in the app.

This was already done in #14 & previous.

**Comment by kellyi** [comment]
I wonder if it would make sense to put the unit in the header somehow, like "The current temperature in the Schuylkill is:" etc.

**Comment by ajrobbins** [comment]
These are all good ideas - I'd like to have a designer take a quick pass at it next sprint as well.
