### ISSUE TITLE
Bucket Turbidity Numbers

### ISSUE THREAD

**Issue by rajadain** [azavea/pwd-river-dispatches#16]
Turbidity results from the API are numeric and in formazin nephelometric units (FNU): https://waterdata.usgs.gov/nwis/uv/?site_no=01474500

![image](https://user-images.githubusercontent.com/1430060/27355288-76012dee-55d8-11e7-9e0c-822a00bb99f2.png)

Find out how these should be grouped in the buckets of "Very Low", "Low", "Moderate", "High", and "Very High" as shown in the app:

![image](https://user-images.githubusercontent.com/1430060/27355332-a3311612-55d8-11e7-9388-ec444fd611b0.png)

**Comment by rajadain** [comment]
This is a question for Victoria /cc @ajrobbins

**Comment by ajrobbins** [comment]
Just emailed her.

**Comment by ajrobbins** [comment]
Response from Matthew Fritch, environmental engineer at PWD (via Victoria):

>here are my recommendations for the gradation of turbidity levels. These are based on relating the FNU values to inches of visibility in the water. Very High correlates to less than 2.5 inches of visibility; Very Low correlates to greater than 21.6 inches of visibility; and the buckets between are dividing the visibility ranges evenly between the two extremes.
>
> Very High: > 240 FNU
> High: 40.1 - 240 FNU
> Moderate: 17.1 - 40 FNU
> Low: 10.1 - 17 FNU
> Very Low: < 10 FNU
>
> For reference: http://watermonitoring.uwex.edu/pdf/level1/data-DissolvedOxygen.pdf
