### ISSUE TITLE
Investigate API

### ISSUE THREAD

**Issue by kellyi** [azavea/pwd-river-dispatches#2]
https://waterservices.usgs.gov/nwis/iv/?format=json&indent=on&sites=01474500&parameterCd=00060,00065&siteStatus=all

https://waterservices.usgs.gov/rest/IV-Test-Tool.html

**Comment by rajadain** [comment]
Shares points with #5

**Comment by kellyi** [comment]
This link has a summary of the drain along with all its available parameter codes, which is the comma-separated list following `parameterCd`: https://waterdata.usgs.gov/usa/nwis/uv?01474500

**Comment by kellyi** [comment]
I think this has all the parameters:

https://waterservices.usgs.gov/nwis/iv/?format=json&indent=on&sites=01474500&parameterCd=00010,00045,00060,00065,00095,00300,00301,00400,63680,72204,99988&siteStatus=all

**Comment by kellyi** [comment]
Not sure we need or want this but it looks like this link:

https://paapps.er.usgs.gov/webcams/01474500/01474500_12.jpg

Updates with a webcam picture shot from the site, where `_12` seems to represent the hour the picture was taken in a range of `_0` to `_23` representing the 24h value.
