### ISSUE TITLE
Investigate deployment options

### ISSUE THREAD

**Issue by kellyi** [azavea/pwd-river-dispatches#26]
The static file version seems to be returning errors when trying to hit the API endpoints. We should fix this.

**Comment by rajadain** [comment]
Can't find exact documentation for this right away, but `file://` URIs have been disallowed from accessing the internet since as long as I've been developing for the web. That's why we use `localhost`.

**Comment by kellyi** [comment]
Makes sense. We should probably find out whether or not the installation runs some kind of local server to load the app.

**Comment by kellyi** [comment]
This currently runs as a static file loaded directly the browser. To enable making API requests for sensor data, we'll need to figure out a way to serve the app locally such that it can make requests.

**Comment by mmcfarland** [comment]
We've asked them to enable IIS on the computer running the interactive, so we can use it to serve this locally.

**Comment by rajadain** [comment]
In that case, we should consider renaming the main file to `index.html`.

**Comment by kellyi** [comment]
Closing this in favor of a new installer card.

**Comment by kellyi** [comment]
This was deployed; must have forgotten to click close so I'm doing that now.
