### ISSUE TITLE
Test, Package, and Send

### ISSUE THREAD

**Issue by rajadain** [azavea/pwd-river-dispatches#8]
- [x] Test the app to ensure it works well, both in online and offline conditions.
- [x] Package the app with our changes over the original ZIP
~- [ ] Send to client~ (to be handled in #25)

**Comment by kellyi** [comment]
Looks like we may not currently be handling the xhr 'error' case, so I'll put up a PR for that.

**Comment by kellyi** [comment]
Put up #21 to handle offline support.

**Comment by kellyi** [comment]
I think this is mostly ready to go once we have the outstanding PRs in.

#21 adds offline support
#20 sets up the project to build a zip file

Once those are in we'll have something to send.

**Comment by rajadain** [comment]
Thanks. These definitely _are_ on my radar, will get to reviewing them later today.

**Comment by ajrobbins** [comment]
We'll need to wait for a design pass before sending, so I'd say #21 and #20 are sufficient to satisfy this card.

**Comment by kellyi** [comment]
Sounds good. I'm going to move this to verified and I think we should open another card for QA testing and sending the the file, as the first two items in the original comment here have been taken care of.

**Comment by ajrobbins** [comment]
Sounds good!

**Comment by kellyi** [comment]
Made #25 for the rest of this.
